image: "python:3.7"

before_script:
  - python --version
  - pip install pipenv
  - pipenv install -d

stages:
  - test

test:
  stage: test
  script:
  - pipenv run pytest --cov=./ -n 17
  - pipenv run coverage report -m
  coverage: '/TOTAL.+ ([0-9]{1,3}%)/'
