image: "python:3.7"

before_script:
  - python --version
  - pip install pipenv
  - pipenv install -d

stages:
  - test

test:
  stage: test
  only:
    - develop   # TODO: Change to master
  script:
  - pipenv run pytest --cov=./src
  - pipenv run coverage report -m
  coverage: '/TOTAL.+ ([0-9]{1,3}%)/'
